# Generated by Django 5.1.7 on 2025-08-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_employer_user_is_jobseeker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicant',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='views',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='portfolio_link',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.job'),
        ),
    ]
