# Generated by Django 5.2.5 on 2025-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_profile_picture_user_resume_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
