# Generated by Django 5.2.5 on 2025-08-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_job_salary_job_salary_max_job_salary_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='deadline',
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
