# Generated by Django 5.2.5 on 2025-08-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description_pdf',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='A brief summary of the job.'),
        ),
    ]
